/**
 * The recorded-input ports of a Genesis-Live epoch (design §4.F, phase L3b).
 *
 * Only the interfaces live here; the implementations are under
 * `src/lab/live/`. The split is not cosmetic: `world.ts` and `genesis.ts` must
 * name these types, and the science guard
 * (`.github/scripts/check-live-isolation.mjs`) forbids the scientific
 * instruments — which reach both files — from importing anything under
 * `src/lab/live/`, even type-only. So the contract sits beside the shared
 * rules of `epoch-rules.ts`, outside that directory, exactly as the injected
 * live policy factory does.
 *
 * What every port here has in common: it turns something the seed cannot
 * reproduce into a value the world commits as an event, and from then on the
 * evidence — not the port — is what replay reads. A replay of a live epoch
 * never constructs any of these.
 */
import type { CognitionUsage } from "./cognition.js";
import type { LabTaskState, PressureSpec, SubmissionState } from "./types.js";

/**
 * Recorded work entering the world from outside (`tasks/inbox.jsonl`).
 *
 * The calibration stream is NOT behind this port. It stays where it always
 * was — one `DeterministicTaskStream` owned by the world and regenerated by
 * the protocol verifier — because a second calibration generator is exactly
 * the drift the single-embodiment invariant forbids. This port supplies only
 * what the seed cannot produce.
 */
export interface LiveTaskSource {
  readonly id: string;
  /**
   * The external tasks that enter on `tick`, in the order they were recorded
   * and at most `capacity` of them (the live world is bounded by
   * `taskStream.maxBacklog`, and a recorded task is bound to its own tick).
   */
  next(tick: number, capacity: number, signal?: AbortSignal): Promise<LabTaskState[]>;
}

/** One recorded verdict on one submission of recorded work. */
export interface LiveVerdict {
  /** Identity of the port that produced it; must be the manifest's `evaluatorId`. */
  evaluatorId: string;
  /** The grader's answer, verbatim and unparsed — the recorded input itself. */
  content: string;
  usage: CognitionUsage;
  /** Quality in parts per million; the reward is paid in proportion to it. */
  qualityPpm: number;
}

export interface LiveEvaluationRequest {
  task: LabTaskState;
  submission: SubmissionState;
  tick: number;
}

/**
 * Grades work no oracle can grade. Calibration tasks never reach it: they
 * carry a hidden oracle and are graded by `IndependentEvaluator`, the one
 * evaluator the scientific track has always used.
 */
export interface LiveEvaluatorPort {
  readonly id: string;
  evaluate(request: LiveEvaluationRequest, signal?: AbortSignal): Promise<LiveVerdict>;
}

/**
 * Operator physics (`physics/inbox.jsonl`).
 *
 * The control plane sets physics and nothing else — prices, capacities, load,
 * and the retirement share, which is still drawn from `pressureRng`. A record
 * addressed to an individual agent is refused by the parser, not ignored by
 * the world: steering one agent is the boundary this port exists to hold.
 */
export interface LivePressureSource {
  readonly id: string;
  /** The pressures that apply on `tick`, in recorded order. */
  next(tick: number, signal?: AbortSignal): Promise<PressureSpec[]>;
}

/** The three recorded-input ports of one live epoch. */
export interface LiveRecordedInputs {
  taskSource?: LiveTaskSource;
  evaluator?: LiveEvaluatorPort;
  pressureSource?: LivePressureSource;
}
